### PR TITLE
Add arm-x19 template folder

### PR DESCRIPTION
**Pull request by boretom**
I adapted the build scripts a tiny bit to create arm-x19 packages. For that to work you'll need my other pull request for the plex-media-server-distro-scripts repository.

I do realize that you just disabled QNAP in your build process but I thought I create the request anyway :)

Have a good day
# 

... and move shared/plex.sh to x86_template
since that script won't work on QNAP arm-x19

### CODE REVIEW

**Comment by boretom** [comment]
That pull request is of course now out-of-date since another build environment is used.

**Comment by elan** [comment]
Doh! Sorry. We revamped it when we moved to the new upgraded build infrastructure.

**Comment by boretom** [comment]
Null problemo :) ... I've taled to Dani22 on the forum and I guess the non-chroot option that is now at work it easier for Tobias. I'll create a little patch for the new build system and will see what happens :o)

**Comment by elan** [comment]
You rock, thanks :)

**Pull request closed without merging**
